#!/bin/bash
IMAGE_NAMES=()
IMAGE_NAMES+=('reifan49/py.misskey-simple-scheduler')

TARGET_TAG=$(git describe --tags --abbrev=0 2>/dev/null)
if [[ -n "${TARGET_TAG}" ]]; then
  TARGET_TAG=$(echo "${TARGET_TAG}" | grep --color=none -ohE '([0-9]+(\.[0-9]+)*)' | head -n 1)
else
  echo "Target tag is not detected. Using latest as fallback" >&2
fi

IMAGE_TAGS=()
for image_name in "${IMAGE_NAMES[@]}"; do
  if [[ -n "${TARGET_TAG}" ]]; then
    IMAGE_TAGS+=("-t" "${image_name}:${TARGET_TAG}")
  else
    IMAGE_TAGS+=("-t" "${image_name}")
  fi
done

if [[ "${#IMAGE_TAGS[@]}" -le 0 ]]; then
  echo 'No tags assigned for the build. Halting.' >&2
  exit 1
fi

REMOTE_NAME=$(
  git branch --format='%(HEAD) %(refname:short) %(upstream:short)' | \
    grep -E '^\*' | awk '{ print $3 }' | cut -d/ -f1
)
REMOTE_URL=$(git remote get-url "${REMOTE_NAME}")
REMOTE_URL_LABEL=
[[ -n ${REMOTE_URL} ]] && REMOTE_URL_LABEL="--label org.opencontainers.image.source=${REMOTE_URL}"

docker build "${IMAGE_TAGS[@]}" \
  ${REMOTE_URL_LABEL} \
  --label org.opencontainers.image.licenses=BSD-3-Clause-Clear \
  .